version: '3.9'

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

<<<<<<< HEAD
   db:
     image: postgres:13
     volumes:
      - dev-db-data:/var/lib/postgresql/data
     environment:
      - POSTGRES_PASSWORD=postgres
    
volumes:
   dev-db-data:
=======
  db:
    image: postgres:13
    volumes:
     - dev-db-data:/var/lib/postgresql/data
    environment: 
     - POSTGRES_PASSWORD=postgres
     

volumes:
  dev-db-data: 
>>>>>>> 00447ee5db49eb2f6b65771444b9480291aa3dad
